[tasks.dev]
command = "cargo"
args = ["run"]

[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.validate]
command = "cargo"
args = ["run", "--bin", "validate"]

[tasks.test]
command = "cargo"
args = ["test"]
